#





http:
  port: 8001
  # [可选] HTTPS配置， 默认不开启
  #ssl:
  #  # [可选] 是否开启HTTPS访问
  #  enabled: false
  #  # [可选] 证书文件路径，放置在resource/目录下即可，修改xxx为文件名
  #  key-store: classpath:test.monitor.89iot.cn.jks
  #  # [可选] 证书密码
  #  key-store-password: gpf64qmw
  #  # [可选] 证书类型， 默认为jks，根据实际修改
  #  key-store-type: JKS
    

rtc:

    ips:
        -  192.168.9.174

    udp:
        port: 10001
    tcp:
        port: 20001
     
    cert: fullchain.pem
    key:  privkey.pem



rtp:
    
    tcp:
        min_port: 20000
        max_port: 30000
    udp:
        min_port: 20000
        max_port: 30000